import { NextRequest, NextResponse } from 'next/server'
import { verifySupabaseToken } from '@/lib/supabase-admin'
import { ensureUserProfile } from '@/lib/user-profile'
import { SupabaseDB } from '@/lib/supabase-db'
import { getTemplateById } from '@/lib/book-templates'
import { generateBookCoverAsync } from '@/lib/auto-cover-generator'

// POST /api/books/from-template
// Entry point: creates the book database record, sets up the chapter structure from the
// chosen template, and (when autoGenerate=true) kicks off AI content generation by calling
// /api/books/generate-from-template asynchronously in the background.
// Frontend calls this endpoint directly (BookTemplateSelector).
// Do NOT merge with /api/books/generate-from-template — they serve distinct roles:
// this one is the synchronous initialiser; the other is the long-running AI worker.
export async function POST(req: NextRequest) {
  try {
    const authorization = req.headers.get('authorization')
    const token = authorization?.replace('Bearer ', '')

    if (!token) {
      return NextResponse.json({ error: 'No token provided' }, { status: 401 })
    }

    const user = await verifySupabaseToken(token)

    if (!user || !user.userId) {
      return NextResponse.json({ error: 'Invalid token' }, { status: 401 })
    }

    // Ensure user profile exists
    if (user.email) {
      await ensureUserProfile(user.userId, user.email)
    }

    const { templateId, customTitle, autoGenerate = true, customSettings } = await req.json()

    if (!templateId) {
      return NextResponse.json({ error: 'Template ID is required' }, { status: 400 })
    }

    // Get template
    const template = getTemplateById(templateId)
    if (!template) {
      return NextResponse.json({ error: 'Template not found' }, { status: 404 })
    }

    // Use custom settings if provided, otherwise fall back to template defaults
    const effectiveChapters = customSettings?.chapters ?? template.chapters
    const effectiveGenre = customSettings?.genre ?? template.genre
    const effectiveStyle = customSettings?.style ?? template.style
    const effectiveTargetAudience = customSettings?.targetAudience ?? template.targetAudience
    const effectivePrompt = customSettings?.prompt ?? template.samplePrompt ?? ''
    const effectiveDescription = customSettings?.description ?? template.description

    // Create chapter structure - either use template outline or generate placeholder chapters
    let chapters
    if (effectiveChapters <= template.chapterOutline.length) {
      // Use existing chapter outlines up to the requested number
      chapters = template.chapterOutline.slice(0, effectiveChapters).map((chapter, index) => ({
        id: String(index + 1),
        title: chapter.title,
        content: '', // Will be filled by AI
        wordCount: 0,
        description: chapter.description,
        estimatedWords: chapter.estimatedWords
      }))
    } else {
      // Use all template chapters and generate placeholders for additional ones
      chapters = template.chapterOutline.map((chapter, index) => ({
        id: String(index + 1),
        title: chapter.title,
        content: '',
        wordCount: 0,
        description: chapter.description,
        estimatedWords: chapter.estimatedWords
      }))

      // Add placeholder chapters for the remaining count
      const avgWordsPerChapter = Math.round(
        template.chapterOutline.reduce((sum, ch) => sum + ch.estimatedWords, 0) / template.chapterOutline.length
      )
      for (let i = template.chapterOutline.length; i < effectiveChapters; i++) {
        chapters.push({
          id: String(i + 1),
          title: `Chapter ${i + 1}`,
          content: '',
          wordCount: 0,
          description: 'Generated by AI',
          estimatedWords: avgWordsPerChapter
        })
      }
    }

    // Determine book title
    const bookTitle = customSettings?.title || customTitle || `${template.name} - New Book`

    // Build the full description with prompt
    const fullDescription = effectivePrompt
      ? `${effectiveDescription}\n\nIdee: ${effectivePrompt}`
      : effectiveDescription

    // Create the book with generating status if autoGenerate is true
    const book = await SupabaseDB.createBook({
      title: bookTitle,
      genre: effectiveGenre,
      description: fullDescription,
      content: '',
      chapters: effectiveChapters,
      style: effectiveStyle,
      target_audience: effectiveTargetAudience,
      book_type: template.bookType,
      user_id: user.userId,
      status: autoGenerate ? 'generating' : 'draft',
      chapters_json: JSON.stringify(chapters),
      images: template.bookType === 'picture' ? [] : null,
      ai_generated: autoGenerate
    })

    // Automatically generate cover in the background (non-blocking)
    if (book.id) {
      generateBookCoverAsync(book.id).catch(err => {
        console.error('Background cover generation failed:', err)
        // Don't throw - this is non-critical
      })
    }

    // If autoGenerate is true, create a generation job and trigger AI generation
    if (autoGenerate) {
      // Create generation job with custom settings
      const job = await SupabaseDB.createBookGenerationJob({
        user_id: user.userId,
        book_id: book.id,
        status: 'pending',
        progress: 0,
        current_step: 'Preparing AI generation...',
        config: {
          templateId,
          template: template.name,
          chapters: effectiveChapters,
          estimatedWords: template.estimatedWords,
          chapterOutline: chapters,
          // Include custom settings for the AI to use
          customSettings: customSettings ? {
            prompt: effectivePrompt,
            genre: effectiveGenre,
            style: effectiveStyle,
            targetAudience: effectiveTargetAudience,
            description: effectiveDescription
          } : null
        }
      })

      const jobId = job.id!

      // Update book with active job ID
      await SupabaseDB.updateBook(book.id!, {
        active_job_id: jobId
      })

      // Trigger AI generation asynchronously
      // We'll call the generation API in the background
      fetch(`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:5000'}/api/books/generate-from-template`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          bookId: book.id,
          jobId: jobId,
          templateId: templateId
        })
      }).catch(err => console.error('Error triggering template generation:', err))

      return NextResponse.json({
        success: true,
        book: {
          ...book,
          chaptersJson: book.chapters_json,
          coverImage: book.cover_image,
          backCoverImage: book.back_cover_image,
          backCoverText: book.back_cover_text,
          bookType: book.book_type,
          targetAudience: book.target_audience,
          publicationDate: book.publication_date,
          createdAt: book.created_at,
          updatedAt: book.updated_at
        },
        jobId: jobId,
        autoGenerate: true
      })
    }

    // If not auto-generating, return the empty book structure
    return NextResponse.json({
      success: true,
      book: {
        ...book,
        chaptersJson: book.chapters_json,
        coverImage: book.cover_image,
        backCoverImage: book.back_cover_image,
        backCoverText: book.back_cover_text,
        bookType: book.book_type,
        targetAudience: book.target_audience,
        publicationDate: book.publication_date,
        createdAt: book.created_at,
        updatedAt: book.updated_at
      },
      autoGenerate: false
    })
  } catch (e) {
    console.error('Error creating book from template:', e instanceof Error ? e.stack : e)
    return NextResponse.json({
      error: e instanceof Error ? e.message : 'Internal server error'
    }, { status: 500 })
  }
}
