-- Add ai_generated field to books table for paywall logic
-- This field tracks whether a book was generated by AI or manually created
-- Used to determine if paywall should be applied (only 1 chapter visible until purchased)

ALTER TABLE public.books
ADD COLUMN ai_generated BOOLEAN DEFAULT false;

-- Add index for better performance when querying AI-generated books
CREATE INDEX idx_books_ai_generated ON public.books(ai_generated) WHERE ai_generated = true;

-- Comment for documentation
COMMENT ON COLUMN public.books.ai_generated IS 'Whether this book was generated by AI (true) or manually created (false). Used for paywall logic.';
